package: nb_anacondacloud

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-32
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build conda.recipe -c anaconda-nb-extensions -c javascript -c mutirri -c jakirkham -c bokeh

build_targets: conda

---

platform: win-32
engine: python=2.7
exclude: true
