name: nb_anacondacloud
channels:
  - anaconda-nb-extensions
  - javascript
  - cpcloud
dependencies:
  - anaconda-client
  - coverage
  - flake8
  - mock
  - nb_config_manager
  - nbsetuptools
  - nodejs
  - nose
  - notebook
  - pyyaml
  - npm # [win]
