name: nb_anacondacloud
channels:
  - anaconda-nb-extensions
  - javascript
dependencies:
  - anaconda-client
  - mock
  - nb_config_manager
  - nbsetuptools
  - nodejs
  - nose
  - notebook
  - pyyaml
